<?php

namespace App\Http\Controllers;

use App\Models\Location;
use App\Models\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Inertia\Inertia;
use Inertia\Response;
use Illuminate\Http\RedirectResponse;

class LocationController extends Controller
{
    /**
     * Display a listing of the locations.
     */
    public function index(): Response|RedirectResponse
    {
        $user = Auth::user();
        $company = $user->currentCompany();
        
        // If user doesn't have a company, redirect to create one
        if (!$company) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        $locations = Location::where('company_id', $company->id)
            ->with(['assets'])
            ->withCount(['assets'])
            ->latest()
            ->paginate(12);

        return Inertia::render('Locations/Index', [
            'locations' => $locations,
            'company' => $company,
        ]);
    }

    /**
     * Show the form for creating a new location.
     */
    public function create(): Response|RedirectResponse
    {
        $user = Auth::user();
        $company = $user->currentCompany();
        
        // If user doesn't have a company, redirect to create one
        if (!$company) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }

        return Inertia::render('Locations/Create', [
            'company' => $company,
        ]);
    }

    /**
     * Store a newly created location in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $user = Auth::user();
        $company = $user->currentCompany();
        
        // If user doesn't have a company, redirect to create one
        if (!$company) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }

        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'building' => 'nullable|string|max:100',
            'office_number' => 'nullable|string|max:50',
        ]);

        $validated['company_id'] = $company->id;
        // Code will be auto-generated by the model

        $location = Location::create($validated);

        return redirect()->route('locations.show', $location)
            ->with('success', 'Location created successfully.');
    }

    /**
     * Display the specified location.
     */
    public function show(Location $location): Response|RedirectResponse
    {
        $user = Auth::user();
        $company = $user->currentCompany();
        
        // If user doesn't have a company, redirect to create one
        if (!$company) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        // Check if user has access to this location
        if ($location->company_id !== $company->id) {
            abort(403);
        }

        $location->load(['company', 'assets.assetCategory']);
        $location->loadCount(['assets']);

        return Inertia::render('Locations/Show', [
            'location' => $location,
        ]);
    }

    /**
     * Show the form for editing the specified location.
     */
    public function edit(Location $location): Response|RedirectResponse
    {
        $user = Auth::user();
        $company = $user->currentCompany();
        
        // If user doesn't have a company, redirect to create one
        if (!$company) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        // Check if user has access to this location
        if ($location->company_id !== $company->id) {
            abort(403);
        }

        return Inertia::render('Locations/Edit', [
            'location' => $location,
        ]);
    }

    /**
     * Update the specified location in storage.
     */
    public function update(Request $request, Location $location): RedirectResponse
    {
        $user = Auth::user();
        $company = $user->currentCompany();
        
        // If user doesn't have a company, redirect to create one
        if (!$company) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        // Check if user has access to this location
        if ($location->company_id !== $company->id) {
            abort(403);
        }

        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'building' => 'nullable|string|max:100',
            'office_number' => 'nullable|string|max:50',
        ]);

        $location->update($validated);

        return redirect()->route('locations.show', $location)
            ->with('success', 'Location updated successfully.');
    }

    /**
     * Remove the specified location from storage.
     */
    public function destroy(Location $location): RedirectResponse
    {
        $user = Auth::user();
        $company = $user->currentCompany();
        
        // If user doesn't have a company, redirect to create one
        if (!$company) {
            return redirect()->route('companies.create')
                ->with('info', 'Please create a company first to manage locations.');
        }
        
        // Check if user has access to this location
        if ($location->company_id !== $company->id) {
            abort(403);
        }

        // Check if location has assets
        if ($location->assets()->count() > 0) {
            return redirect()->route('locations.index')
                ->with('error', 'Cannot delete location that has assets assigned.');
        }

        $location->delete();

        return redirect()->route('locations.index')
            ->with('success', 'Location deleted successfully.');
    }
}
